name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Wasm Pack
      run: wasm-pack build  --target nodejs
#     - name: Run tests
#       run: cargo test --verbose
